name: wonderpress-coding-standards

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  wonderpress-coding-standards:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Codesniff against the Wonderpress Coding Standards...
      run: composer update && composer run lint
